// src/lib/store-registry-seed.ts (owner WP04): the 67 seed stores of the store brief (Appendix A, in the brief's order) and the 13 ShadowPOS stores, with the ids of tests/fixtures/store-ids.json.
// Every row is "unverified": the first production probe (scripts/probe-stores.ts) admits a store at >= 20 matched in-stock listings and a currency that matches its market (10.26). `collections` is the
// ONE handle the 2026-10-07 probe picked on page 1; discovery (store-import.ts discoverMagicCollections) finds the rest at run time, and 14 of these picks are sub-collections or partial (brief Appendix A "verdict").
// themythicstore.com and thecgrealm.com charge CAD in the US market (`currency`): the importer refuses a store whose currency differs from its market's, so they are listed and never priced.
// APPEND-ONLY: a new store takes max(id) + 1; a removed one moves to RETIRED_STORE_IDS in stores.ts and its id is never reused.
import type { StoreInfo } from "./stores";

export const SEED_STORES: readonly StoreInfo[] = [
  { id: 10, key: "rhysticnostalgiagaming", name: "Rhystic Nostalgia Gaming", base: "https://rhysticnostalgiagaming.com.au", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 11, key: "goodgames", name: "Good Games", base: "https://tcg.goodgames.com.au", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 12, key: "spellroo", name: "Spellroo Gaming", base: "https://spellroogaming.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 13, key: "eternalmagic", name: "Eternal Magic", base: "https://eternalmagic.cc", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 14, key: "elementalarcade", name: "Elemental Arcade", base: "https://elementalarcade.com.au", country: "AU", collections: ["magic-the-gathering-tcg-singles"], status: "unverified" },
  { id: 15, key: "mightycoolgames", name: "Mighty Cool Games", base: "https://mightycoolgames.com.au", country: "AU", collections: ["mtg-singles-available"], status: "unverified" },
  { id: 16, key: "reefsidegames", name: "Reefside Games", base: "https://reefsidegames.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 17, key: "shuffleandcutgames", name: "Shuffle n Cut Melbourne", base: "https://shuffleandcutgames.com", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 18, key: "millenniumcomics", name: "Millennium Comics", base: "https://millenniumcomics.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 19, key: "fabledgames", name: "Fabled Games Hobbies and Collectibles", base: "https://fabledgames.store", country: "AU", collections: ["mtg-8th-edition"], status: "unverified" },
  { id: 20, key: "manamarket", name: "Mana Market", base: "https://manamarket.com.au", country: "AU", collections: ["magic-the-gathering-doctor-who-singles"], status: "unverified" },
  { id: 21, key: "ggmorley", name: "Good Games Morley", base: "https://www.goodgamesmorley.com.au", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 22, key: "collectorsmith", name: "The CollectorSmith", base: "https://www.thecollectorsmith.com.au", country: "AU", collections: ["mtg-singles-gl"], status: "unverified" },
  { id: 23, key: "justcardstuff", name: "Just Card Stuff", base: "https://justcardstuff.com.au", country: "AU", collections: ["tcg-magic-the-gathering-singles-raw"], status: "unverified" },
  { id: 24, key: "laboitemystere", name: "La Boite Mystere", base: "https://laboitemystere.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 25, key: "empiretradings", name: "Empire Trading", base: "https://www.empiretradings.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 26, key: "boutiquelapioche", name: "La Pioche", base: "https://boutiquelapioche.com", country: "CA", collections: ["magic-the-gathering-cartes-a-lunite"], status: "unverified" },
  { id: 27, key: "gametime", name: "GameTime/TempsDuJeu", base: "https://game-time.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 28, key: "facetoface", name: "Face to Face Games", base: "https://facetofacegames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 29, key: "tabletopgiant", name: "Tabletop Giant", base: "https://tabletopgiant.ca", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 30, key: "kapescaping", name: "Kap Escaping", base: "https://kapescaping.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 31, key: "blackrosehobbies", name: "Black Rose Hobbies", base: "https://blackrosehobbies.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 32, key: "carddynasty", name: "Card Dynasty", base: "https://carddynasty.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 33, key: "fusiongamingonline", name: "Fusion Gaming", base: "https://fusiongamingonline.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 34, key: "obsidiangames", name: "Obsidian Games", base: "https://obsidiangames.ca", country: "CA", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 35, key: "lotuspetalgaming", name: "Lotus Petal Gaming", base: "https://lotuspetalgaming.com", country: "CA", collections: ["mtg-singles-1"], status: "unverified" },
  { id: 36, key: "paradoxtcg", name: "ParadoxTCG", base: "https://paradoxtcg.com", country: "CA", collections: ["magic-the-gathering-singles-1"], status: "unverified" },
  { id: 37, key: "cryptmtg", name: "La Crypte", base: "https://cryptmtg.com", country: "CA", collections: ["mtg-unite-tout"], status: "unverified" },
  { id: 38, key: "hairytarantula", name: "Hairy Tarantula", base: "https://www.hairyt.com", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 39, key: "lichcards", name: "Lichcards", base: "https://lichcards.nl", country: "EU", collections: ["avatar-the-last-airbender-magic"], status: "unverified" },
  { id: 40, key: "timetwister", name: "Timetwister Games", base: "https://timetwistergames.it", country: "EU", collections: ["avatar-the-last-airbender-magic"], status: "unverified" },
  { id: 41, key: "trextcg", name: "T-REX TCG", base: "https://www.t-rextcg.com", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 42, key: "magicianscircle", name: "Magician's Circle", base: "https://www.magicians-circle.com", country: "EU", collections: ["carte-singole-magic"], status: "unverified" },
  { id: 43, key: "battlebearkl", name: "Battle Bear Kaiserslautern", base: "https://battle-bear-kl.de", country: "EU", collections: ["magic-einzelkarten"], status: "unverified" },
  { id: 44, key: "brints", name: "Brints Collectibles", base: "https://brintsco.com", country: "SG", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 45, key: "hideoutsg", name: "Hideout", base: "https://hideoutcg.com", country: "SG", collections: ["mtg-singles"], status: "unverified" },
  { id: 46, key: "livingrealms", name: "Living Realms", base: "https://livingrealms.co.uk", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 47, key: "sidequestgames", name: "Side Quest Games", base: "https://www.sidequestgames.uk", country: "UK", collections: ["magic-singles"], status: "unverified" },
  { id: 48, key: "yardsgames", name: "Yard's Games", base: "https://yardsgames.com", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 49, key: "evolutiontcg", name: "Evolution Trading Cards", base: "https://evolutiontradingcards.co.uk", country: "UK", collections: ["magic-single"], status: "unverified" },
  { id: 50, key: "stylecreep", name: "Stylecreep", base: "https://www.stylecreep.com", country: "UK", collections: ["magic-the-gathering-1"], status: "unverified" },
  { id: 51, key: "impactleague", name: "Impact League TCG", base: "https://impactleaguetcg.co.uk", country: "UK", collections: ["mtg-singles"], status: "unverified" },
  { id: 52, key: "collectbydesign", name: "Collect by Design", base: "https://www.collectbydesign.co.uk", country: "UK", collections: ["magic-the-gathering-single-cards"], status: "unverified" },
  { id: 53, key: "gatheringpointgames", name: "Gathering Point Games", base: "https://gatheringpointgames.co.uk", country: "UK", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 54, key: "dicesaloon", name: "Dice Saloon", base: "https://dicesaloonsingles.co.uk", country: "UK", collections: ["friday-night-magic-2014"], status: "unverified" },
  { id: 55, key: "boardsandswords", name: "Boards & Swords", base: "https://boardsandswords.co.uk", country: "UK", collections: ["friday-night-magic-2017"], status: "unverified" },
  { id: 56, key: "thegrumpygoblin", name: "The Grumpy Goblin", base: "https://thegrumpygoblin.co.uk", country: "UK", collections: ["friday-night-magic-2016"], status: "unverified" },
  { id: 57, key: "seventhcity", name: "7th City Collectables", base: "https://7thcitycollectables.com", country: "UK", collections: ["friday-night-magic-2003"], status: "unverified" },
  { id: 58, key: "trainerlegacy", name: "Trainer Legacy", base: "https://www.trainerlegacy.com", country: "UK", collections: ["magic-singles-in-stock"], status: "unverified" },
  { id: 59, key: "atomilicollectables", name: "ATOMILI COLLECTABLES", base: "https://atomilicollectables.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 60, key: "magicandmonsters", name: "Magic and Monsters", base: "https://www.magicandmonsters.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 61, key: "pokeboxusa", name: "PokeBox USA", base: "https://www.pokeboxusa.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 62, key: "stompinggrounds", name: "Stomping Grounds TCG", base: "https://singles.stompinggroundstcg.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 63, key: "mightymeeple", name: "The Mighty Meeple", base: "https://mightymeeple.com", country: "US", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 64, key: "mistymountain", name: "Misty Mountain Games", base: "https://www.mistymountaingames.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 65, key: "cgrealm", name: "The CG Realm", base: "https://thecgrealm.com", country: "US", currency: "CAD", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 66, key: "gatorscardden", name: "Gator's Card Den", base: "https://gatorscardden.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 67, key: "manyrealms", name: "Many Realms", base: "https://manyrealms.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 68, key: "151collectables", name: "151Collectables", base: "https://151collectables.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 69, key: "cardboardanddie", name: "Cardboard and Die", base: "https://cardboardanddie.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 70, key: "grognardgames", name: "Grognard Games", base: "https://grognardgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 71, key: "mysterymtg", name: "Mystery MTG", base: "https://mysterymtg.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 72, key: "cardxcards", name: "Card x Cards", base: "https://cardxcards.com", country: "US", collections: ["magic-the-gathering-singles-in-stock"], status: "unverified" },
  { id: 73, key: "thegamecornergames", name: "The Game Corner", base: "https://www.thegamecornergames.com", country: "US", collections: ["mtg-single"], status: "unverified" },
  { id: 74, key: "zulusgames", name: "Zulus Games", base: "https://zulusgames.com", country: "US", collections: ["magic-dominaria-remastered"], status: "unverified" },
  { id: 75, key: "mythicstore", name: "The Mythic Store", base: "https://themythicstore.com", country: "US", currency: "CAD", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 76, key: "bardsandcards", name: "Bards & Cards", base: "https://singles.bardsandcards.com", country: "US", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 77, key: "lotusgamesct", name: "Lotus Games (Colchester)", base: "https://lotusgamesltd.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 78, key: "evolutiongamestx", name: "Evolution Games", base: "https://evolutiontcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 79, key: "secondhandsoldiers", name: "Secondhand Soldiers", base: "https://secondhandsoldiers.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 80, key: "jjaspertcg", name: "Jumping Jasper", base: "https://jjaspertcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 81, key: "theorcslair", name: "The Orc's Lair", base: "https://theorcslair.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 82, key: "spellboundtx", name: "Spellbound Cards & Games", base: "https://spellboundtx.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 83, key: "metatcg", name: "Meta TCG", base: "https://metatcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 84, key: "gameandcompany", name: "Game & Company", base: "https://gameandcompany.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 85, key: "feisgames", name: "Fei's Games", base: "https://feisgames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 86, key: "koboldskeep", name: "Kobold's Keep", base: "https://koboldskeep.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 87, key: "haikugaming", name: "Haiku Gaming", base: "https://haikugaming.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 88, key: "thecleverkobold", name: "The Clever Kobold", base: "https://thecleverkobold.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 89, key: "darksidegames", name: "Darkside Games", base: "https://darksidegames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
];
