// src/lib/store-registry-seed.ts (owner WP04): the 67 seed stores of the store brief (Appendix A, in the brief's order) and the 13 ShadowPOS stores, with the ids of tests/fixtures/store-ids.json.
// Every row is "unverified": the first production probe (scripts/probe-stores.ts) admits a store at >= 20 matched in-stock listings and a currency that matches its market (10.26). `collections` is the
// store's main Magic singles collection, read first and to its end (or Shopify's 25,000-product window); discovery (store-import.ts discoverMagicCollections) finds the rest at run time. The 2026-10-07 probe
// picked one handle on page 1 and 14 of those were sub-collections; on 2026-10-09 18 rows were corrected from `/collections/<h>.json` products_count and page 1 through the matcher: the in-stock
// collection where the store has one (goodgames 44,239, tabletopgiant 26,142, gatheringpointgames 30,936, mightymeeple 27,848, cryptmtg "mtg-unite-stock" 58,813, boutiquelapioche "...-en-stock"
// 9,117 of 171,272, gametime "magic-the-gathering" 4,367 of 117,380, ggmorley "see-more-mtg" 26,237), else the all-singles one instead of a single set or a Friday Night Magic promo list (fabledgames,
// manamarket, lichcards, timetwister, dicesaloon, boardsandswords, thegrumpygoblin, seventhcity, zulusgames, bardsandcards). Edit a handle only; never an id, key or base.
// themythicstore.com and thecgrealm.com charge CAD in the US market (`currency`): the importer refuses a store whose currency differs from its market's, so they are listed and never priced.
// APPEND-ONLY: a new store takes max(id) + 1; a removed one moves to RETIRED_STORE_IDS in stores.ts and its id is never reused.
import type { StoreInfo } from "./stores";

export const SEED_STORES: readonly StoreInfo[] = [
  { id: 10, key: "rhysticnostalgiagaming", name: "Rhystic Nostalgia Gaming", base: "https://rhysticnostalgiagaming.com.au", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 11, key: "goodgames", name: "Good Games", base: "https://tcg.goodgames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 12, key: "spellroo", name: "Spellroo Gaming", base: "https://spellroogaming.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 13, key: "eternalmagic", name: "Eternal Magic", base: "https://eternalmagic.cc", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 14, key: "elementalarcade", name: "Elemental Arcade", base: "https://elementalarcade.com.au", country: "AU", collections: ["magic-the-gathering-tcg-singles"], status: "unverified" },
  { id: 15, key: "mightycoolgames", name: "Mighty Cool Games", base: "https://mightycoolgames.com.au", country: "AU", collections: ["mtg-singles-available"], status: "unverified" },
  { id: 16, key: "reefsidegames", name: "Reefside Games", base: "https://reefsidegames.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 17, key: "shuffleandcutgames", name: "Shuffle n Cut Melbourne", base: "https://shuffleandcutgames.com", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 18, key: "millenniumcomics", name: "Millennium Comics", base: "https://millenniumcomics.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 19, key: "fabledgames", name: "Fabled Games Hobbies and Collectibles", base: "https://fabledgames.store", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 20, key: "manamarket", name: "Mana Market", base: "https://manamarket.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 21, key: "ggmorley", name: "Good Games Morley", base: "https://www.goodgamesmorley.com.au", country: "AU", collections: ["see-more-mtg"], status: "unverified" },
  { id: 22, key: "collectorsmith", name: "The CollectorSmith", base: "https://www.thecollectorsmith.com.au", country: "AU", collections: ["mtg-singles-gl"], status: "unverified" },
  { id: 23, key: "justcardstuff", name: "Just Card Stuff", base: "https://justcardstuff.com.au", country: "AU", collections: ["tcg-magic-the-gathering-singles-raw"], status: "unverified" },
  { id: 24, key: "laboitemystere", name: "La Boite Mystere", base: "https://laboitemystere.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 25, key: "empiretradings", name: "Empire Trading", base: "https://www.empiretradings.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 26, key: "boutiquelapioche", name: "La Pioche", base: "https://boutiquelapioche.com", country: "CA", collections: ["magic-the-gathering-cartes-a-lunite-en-stock"], status: "unverified" },
  { id: 27, key: "gametime", name: "GameTime/TempsDuJeu", base: "https://game-time.ca", country: "CA", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 28, key: "facetoface", name: "Face to Face Games", base: "https://facetofacegames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 29, key: "tabletopgiant", name: "Tabletop Giant", base: "https://tabletopgiant.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 30, key: "kapescaping", name: "Kap Escaping", base: "https://kapescaping.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 31, key: "blackrosehobbies", name: "Black Rose Hobbies", base: "https://blackrosehobbies.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 32, key: "carddynasty", name: "Card Dynasty", base: "https://carddynasty.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 33, key: "fusiongamingonline", name: "Fusion Gaming", base: "https://fusiongamingonline.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 34, key: "obsidiangames", name: "Obsidian Games", base: "https://obsidiangames.ca", country: "CA", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 35, key: "lotuspetalgaming", name: "Lotus Petal Gaming", base: "https://lotuspetalgaming.com", country: "CA", collections: ["mtg-singles-1"], status: "unverified" },
  { id: 36, key: "paradoxtcg", name: "ParadoxTCG", base: "https://paradoxtcg.com", country: "CA", collections: ["magic-the-gathering-singles-1"], status: "unverified" },
  { id: 37, key: "cryptmtg", name: "La Crypte", base: "https://cryptmtg.com", country: "CA", collections: ["mtg-unite-stock"], status: "unverified" },
  { id: 38, key: "hairytarantula", name: "Hairy Tarantula", base: "https://www.hairyt.com", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 39, key: "lichcards", name: "Lichcards", base: "https://lichcards.nl", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 40, key: "timetwister", name: "Timetwister Games", base: "https://timetwistergames.it", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 41, key: "trextcg", name: "T-REX TCG", base: "https://www.t-rextcg.com", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 42, key: "magicianscircle", name: "Magician's Circle", base: "https://www.magicians-circle.com", country: "EU", collections: ["carte-singole-magic"], status: "unverified" },
  { id: 43, key: "battlebearkl", name: "Battle Bear Kaiserslautern", base: "https://battle-bear-kl.de", country: "EU", collections: ["magic-einzelkarten"], status: "unverified" },
  { id: 44, key: "brints", name: "Brints Collectibles", base: "https://brintsco.com", country: "SG", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 45, key: "hideoutsg", name: "Hideout", base: "https://hideoutcg.com", country: "SG", collections: ["mtg-singles"], status: "unverified" },
  { id: 46, key: "livingrealms", name: "Living Realms", base: "https://livingrealms.co.uk", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 47, key: "sidequestgames", name: "Side Quest Games", base: "https://www.sidequestgames.uk", country: "UK", collections: ["magic-singles"], status: "unverified" },
  { id: 48, key: "yardsgames", name: "Yard's Games", base: "https://yardsgames.com", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 49, key: "evolutiontcg", name: "Evolution Trading Cards", base: "https://evolutiontradingcards.co.uk", country: "UK", collections: ["magic-single"], status: "unverified" },
  { id: 50, key: "stylecreep", name: "Stylecreep", base: "https://www.stylecreep.com", country: "UK", collections: ["magic-the-gathering-1"], status: "unverified" },
  { id: 51, key: "impactleague", name: "Impact League TCG", base: "https://impactleaguetcg.co.uk", country: "UK", collections: ["mtg-singles"], status: "unverified" },
  { id: 52, key: "collectbydesign", name: "Collect by Design", base: "https://www.collectbydesign.co.uk", country: "UK", collections: ["magic-the-gathering-single-cards"], status: "unverified" },
  { id: 53, key: "gatheringpointgames", name: "Gathering Point Games", base: "https://gatheringpointgames.co.uk", country: "UK", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 54, key: "dicesaloon", name: "Dice Saloon", base: "https://dicesaloonsingles.co.uk", country: "UK", collections: ["mtg-singles"], status: "unverified" },
  { id: 55, key: "boardsandswords", name: "Boards & Swords", base: "https://boardsandswords.co.uk", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 56, key: "thegrumpygoblin", name: "The Grumpy Goblin", base: "https://thegrumpygoblin.co.uk", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 57, key: "seventhcity", name: "7th City Collectables", base: "https://7thcitycollectables.com", country: "UK", collections: ["magic-the-gathering-all-singles"], status: "unverified" },
  { id: 58, key: "trainerlegacy", name: "Trainer Legacy", base: "https://www.trainerlegacy.com", country: "UK", collections: ["magic-singles-in-stock"], status: "unverified" },
  { id: 59, key: "atomilicollectables", name: "ATOMILI COLLECTABLES", base: "https://atomilicollectables.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 60, key: "magicandmonsters", name: "Magic and Monsters", base: "https://www.magicandmonsters.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 61, key: "pokeboxusa", name: "PokeBox USA", base: "https://www.pokeboxusa.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 62, key: "stompinggrounds", name: "Stomping Grounds TCG", base: "https://singles.stompinggroundstcg.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 63, key: "mightymeeple", name: "The Mighty Meeple", base: "https://mightymeeple.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 64, key: "mistymountain", name: "Misty Mountain Games", base: "https://www.mistymountaingames.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 65, key: "cgrealm", name: "The CG Realm", base: "https://thecgrealm.com", country: "US", currency: "CAD", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 66, key: "gatorscardden", name: "Gator's Card Den", base: "https://gatorscardden.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 67, key: "manyrealms", name: "Many Realms", base: "https://manyrealms.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 68, key: "151collectables", name: "151Collectables", base: "https://151collectables.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 69, key: "cardboardanddie", name: "Cardboard and Die", base: "https://cardboardanddie.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 70, key: "grognardgames", name: "Grognard Games", base: "https://grognardgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 71, key: "mysterymtg", name: "Mystery MTG", base: "https://mysterymtg.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 72, key: "cardxcards", name: "Card x Cards", base: "https://cardxcards.com", country: "US", collections: ["magic-the-gathering-singles-in-stock"], status: "unverified" },
  { id: 73, key: "thegamecornergames", name: "The Game Corner", base: "https://www.thegamecornergames.com", country: "US", collections: ["mtg-single"], status: "unverified" },
  { id: 74, key: "zulusgames", name: "Zulus Games", base: "https://zulusgames.com", country: "US", collections: ["magic-single"], status: "unverified" },
  { id: 75, key: "mythicstore", name: "The Mythic Store", base: "https://themythicstore.com", country: "US", currency: "CAD", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 76, key: "bardsandcards", name: "Bards & Cards", base: "https://singles.bardsandcards.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 77, key: "lotusgamesct", name: "Lotus Games (Colchester)", base: "https://lotusgamesltd.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 78, key: "evolutiongamestx", name: "Evolution Games", base: "https://evolutiontcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 79, key: "secondhandsoldiers", name: "Secondhand Soldiers", base: "https://secondhandsoldiers.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 80, key: "jjaspertcg", name: "Jumping Jasper", base: "https://jjaspertcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 81, key: "theorcslair", name: "The Orc's Lair", base: "https://theorcslair.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 82, key: "spellboundtx", name: "Spellbound Cards & Games", base: "https://spellboundtx.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 83, key: "metatcg", name: "Meta TCG", base: "https://metatcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 84, key: "gameandcompany", name: "Game & Company", base: "https://gameandcompany.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 85, key: "feisgames", name: "Fei's Games", base: "https://feisgames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 86, key: "koboldskeep", name: "Kobold's Keep", base: "https://koboldskeep.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 87, key: "haikugaming", name: "Haiku Gaming", base: "https://haikugaming.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 88, key: "thecleverkobold", name: "The Clever Kobold", base: "https://thecleverkobold.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 89, key: "darksidegames", name: "Darkside Games", base: "https://darksidegames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  // Added 2026-10-09 by the store expansion sweep (web search, directories, sister-site registries), each admitted by the batch probe (>= 20 matched in-stock listings, market currency).
  { id: 90, key: "88gamesarena", name: "88 Games Arena", base: "https://88gamesarena.com.au", country: "AU", collections: ["mtg-singles-australia-88-games-arena"], status: "unverified" },
  { id: 91, key: "roningames", name: "Ronin Games", base: "https://roningames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 92, key: "tcgsingles", name: "TCG Singles Australia", base: "https://tcgsingles.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 93, key: "progamers", name: "Pro Gamers", base: "https://progamers.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 94, key: "thecardhubaustralia", name: "The Cardhub Australia", base: "https://thecardhubaustralia.com.au", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 95, key: "thehallofheroes", name: "The Hall of Heroes", base: "https://thehallofheroes.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 96, key: "crackingtcgsingles", name: "Cracking TCG Singles", base: "https://cracking-tcgsingles.com.au", country: "AU", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 97, key: "area52", name: "Area52 Hobart", base: "https://shop.area52.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 98, key: "dragonslair", name: "Dragon's Lair St Marys", base: "https://dragonslair.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 99, key: "crithit", name: "Critical Hit", base: "https://crithit.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 100, key: "mtgsinglesaustralia", name: "MTG Singles Australia", base: "https://mtgsinglesaustralia.com", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 101, key: "plentyofgames", name: "Plenty of Games", base: "https://plentyofgames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 102, key: "gamesportal", name: "Games Portal", base: "https://gamesportal.com.au", country: "AU", collections: ["magic-singles-instock"], status: "unverified" },
  { id: 103, key: "awgames", name: "Aether Wyvern Games", base: "https://awgames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 104, key: "tabernaclegames", name: "Tabernacle Games", base: "https://tcg.tabernaclegames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 105, key: "cardhouse", name: "Card House", base: "https://cardhouse.com.au", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 106, key: "gameology", name: "Gameology", base: "https://gameology.com.au", country: "AU", collections: ["magic-the-gathering-dominaria-united"], status: "unverified" },
  { id: 107, key: "guf", name: "GUF Games", base: "https://guf.com.au", country: "AU", collections: ["mtg-singles-instock-all-stores"], status: "unverified" },
  { id: 108, key: "shuffled", name: "Shuffled", base: "https://shuffled.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 109, key: "oneplacetcs", name: "One Place Trading Card Shop", base: "https://oneplacetcs.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 110, key: "urbanempirecollectables", name: "Urban Empire Collectables", base: "https://urbanempirecollectables.com", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 111, key: "thegamesdistrict", name: "The Games District", base: "https://thegamesdistrict.com", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 112, key: "kastlecardsandgames", name: "Kastle Cards & Games", base: "https://kastlecardsandgames.com", country: "AU", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 113, key: "inngames", name: "Inn Games", base: "https://inngames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 114, key: "generalgames", name: "General Games", base: "https://generalgames.com.au", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 115, key: "playmantis", name: "Playmantis", base: "https://playmantis.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 116, key: "ozziecollectables", name: "Ozzie Collectables", base: "https://ozziecollectables.com", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 117, key: "obsessiongaming", name: "Obsession Gaming", base: "https://obsessiongaming.com.au", country: "AU", collections: ["all-magic-the-gathering-singles"], status: "unverified" },
  { id: 118, key: "fromthedeepgames", name: "From The Deep Games", base: "https://fromthedeepgames.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 119, key: "irresistibleforce", name: "Irresistible Force", base: "https://tcg.irresistibleforce.com.au", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 120, key: "tabletopcommons", name: "Tabletop Commons", base: "https://tabletopcommons.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 121, key: "rnrhobbies", name: "R&R Hobbies", base: "https://rnrhobbies.com.au", country: "AU", collections: ["mtg-singles"], status: "unverified" },
  { id: 122, key: "hobbycollectorsaustralia", name: "Hobby Collectors Australia", base: "https://hobbycollectorsaustralia.com.au", country: "AU", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 123, key: "online", name: "Lots Moore", base: "https://online.lotsmoore.com.au", country: "AU", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 124, key: "skyfoxgames", name: "SKYFOX GAMES", base: "https://skyfoxgames.com", country: "CA", collections: ["mtg-single-in-stock-no-unreleased-products-events-use-for-discounts-loyalty-rewards"], status: "unverified" },
  { id: 125, key: "tkotoyco", name: "TKO Toy Company", base: "https://tkotoyco.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 126, key: "levelzerogames", name: "Level Zero Games", base: "https://levelzerogames.ca", country: "CA", collections: ["mtg-singles-over-10-in-stock"], status: "unverified" },
  { id: 127, key: "exorgames", name: "Exor Games Charlottetown", base: "https://exorgames.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 128, key: "altf4online", name: "Centre de jeux ALT F4", base: "https://altf4online.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 129, key: "fantasyforged", name: "Fantasy Forged", base: "https://fantasyforged.ca", country: "CA", collections: ["mtg-in-stock-only"], status: "unverified" },
  { id: 130, key: "jacksonqueen", name: "Jack's On Queen", base: "https://jacksonqueen.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 131, key: "kunaigames", name: "KunaiGames", base: "https://kunaigames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 132, key: "everythinggames", name: "Everything Games", base: "https://everythinggames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 133, key: "bastiongames", name: "Bastion Games", base: "https://shop.bastiongames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 134, key: "merchantsinventory", name: "Merchant's Shop La Shop du Marchand", base: "https://merchantsinventory.ca", country: "CA", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 135, key: "hfxgames", name: "HFX Games", base: "https://hfxgames.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 136, key: "totalplay", name: "Total Play", base: "https://totalplay.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 137, key: "destinationretro", name: "Destination Retro", base: "https://destinationretro.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 138, key: "blackknightgames", name: "Black Knight Games", base: "https://blackknightgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 139, key: "bootownsgamesandhobbies", name: "Bootown's Games and Hobbies", base: "https://bootownsgamesandhobbies.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 140, key: "magicartestore", name: "MagiCarte", base: "https://magicartestore.com", country: "CA", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 141, key: "houseofcards", name: "House of Cards", base: "https://houseofcards.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 142, key: "upnorthgames", name: "Up North Games", base: "https://upnorthgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 143, key: "multizone", name: "Multizone: Comics And Games", base: "https://multizone.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 144, key: "chimeragamingonline", name: "Chimera Gaming", base: "https://chimeragamingonline.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 145, key: "trinityhobby", name: "Trinity Hobby", base: "https://trinityhobby.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 146, key: "lecoindujeu", name: "Le Coin du Jeu CA", base: "https://lecoindujeu.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 147, key: "playntradewpg", name: "Play N Trade Winnipeg", base: "https://playntradewpg.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 148, key: "laboutiquemythique", name: "La Boutique Mythique", base: "https://laboutiquemythique.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 149, key: "levelupgames", name: "Level Up Games Canada", base: "https://levelupgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 150, key: "401games", name: "401 Games", base: "https://store.401games.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 151, key: "bordercitygames", name: "Border City Games", base: "https://bordercitygames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 152, key: "cardboardhero", name: "Cardboard Hero", base: "https://cardboardhero.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 153, key: "outoftheboxtcg", name: "Out Of The Box CA", base: "https://outoftheboxtcg.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 154, key: "eventhorizonhobbies", name: "Event Horizon Hobbies CA", base: "https://eventhorizonhobbies.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 155, key: "manalounge", name: "The Mana Lounge", base: "https://manalounge.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 156, key: "enterthebattlefield", name: "Enter The Battlefield", base: "https://enterthebattlefield.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 157, key: "gamebridge", name: "C&C Gamebridge", base: "https://gamebridge.ca", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 158, key: "fanofthesport", name: "Fan of the Sport", base: "https://fanofthesport.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 159, key: "reddragon", name: "Red-DragonCA", base: "https://red-dragon.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 160, key: "mtgjeuxjubes", name: "Jeuxjubes", base: "https://mtgjeuxjubes.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 161, key: "screenfreegames", name: "Screen Free Games", base: "https://screenfreegames.com", country: "CA", collections: ["magic-singles"], status: "unverified" },
  { id: 162, key: "darkfoxtcg", name: "Dark Fox TCG", base: "https://darkfoxtcg.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 163, key: "manaconfluence", name: "Mana Confluence", base: "https://manaconfluence.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 164, key: "borealgaming", name: "Boreal Gaming & Cards", base: "https://borealgaming.com", country: "CA", collections: ["magic-the-gathering-card-singles"], status: "unverified" },
  { id: 165, key: "ergames", name: "East Ridge Games", base: "https://ergames.ca", country: "CA", collections: ["mtg-singles-instock-1"], status: "unverified" },
  { id: 166, key: "tistacards", name: "TistaCards", base: "https://tistacards.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 167, key: "waypointgames", name: "Waypoint Games CA", base: "https://waypointgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 168, key: "derpycards", name: "Derpy Cards", base: "https://derpycards.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 169, key: "thetimevault", name: "The Time Vault CA", base: "https://thetimevault.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 170, key: "hobbiesvilleca", name: "Hobbiesville", base: "https://hobbiesville.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 171, key: "cardboardclassics", name: "Cardboard Classics", base: "https://cardboardclassics.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 172, key: "darkcrystalcardstcg", name: "Dark Crystal Cards TCG", base: "https://darkcrystalcardstcg.com", country: "CA", collections: ["all-mtg-singles"], status: "unverified" },
  { id: 173, key: "deckoutgaming", name: "Deck Out Gaming", base: "https://deckoutgaming.ca", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 174, key: "fafnirshoard", name: "Fafnir's Hoard", base: "https://fafnirshoard.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 175, key: "danireonca", name: "Danireon Cards & Games", base: "https://danireon.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 176, key: "animealley", name: "Anime Alley", base: "https://animealley.ca", country: "CA", collections: ["magic-singles"], status: "unverified" },
  { id: 177, key: "northernwartable", name: "Northern War Table", base: "https://northernwartable.com", country: "CA", collections: ["magic-the-gathering-singles-test"], status: "unverified" },
  { id: 178, key: "playerscandc", name: "PLAYERS CARDS AND COLLECTIBLES", base: "https://playerscandc.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 179, key: "gameknight", name: "GameKnight Games", base: "https://gameknight.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 180, key: "pandorasboox", name: "Pandora's Boox", base: "https://pandorasboox.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 181, key: "gtgames", name: "GT Games", base: "https://gtgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 182, key: "ubecard", name: "UBECARD.COM", base: "https://ubecard.com", country: "CA", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 183, key: "gamerszone", name: "GamersZone", base: "https://gamerszone.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 184, key: "underthemountain", name: "Under the Mountain Games", base: "https://underthemountain.games", country: "CA", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 185, key: "forestcitycollectibles", name: "Forest City Collectibles", base: "https://forestcitycollectibles.com", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 186, key: "taverneducollectionneur", name: "Taverne du Collectionneur", base: "https://taverneducollectionneur.com", country: "CA", collections: ["mtg-instock"], status: "unverified" },
  { id: 187, key: "negativezonecomics", name: "Negative Zone Comics", base: "https://negativezonecomics.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 188, key: "cardsandcoasters", name: "Cards and Coasters CA", base: "https://cardsandcoasters.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 189, key: "cardcastergames", name: "Card Caster", base: "https://cardcastergames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 190, key: "tcgandgames", name: "TCG and Games", base: "https://tcgandgames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 191, key: "infinitycards", name: "Infinity Cards & Collectibles", base: "https://infinitycards.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 192, key: "boutiquelechevalier", name: "Boutique Le Chevalier", base: "https://boutiquelechevalier.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 193, key: "kingdomtitans", name: "Kingdom of the Titans (Cards)", base: "https://kingdomtitans.cards", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 194, key: "toysnowman", name: "Toy Snowman", base: "https://toysnowman.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 195, key: "mechagames", name: "Mecha Games", base: "https://mechagames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 196, key: "vortexgames", name: "Vortex Games", base: "https://vortexgames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 197, key: "dungeoncomicsandcards", name: "Dungeon Comics & Cards", base: "https://dungeoncomicsandcards.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 198, key: "itsgametime", name: "Game Time Collectibles", base: "https://itsgametime.ca", country: "CA", collections: ["magic-singles-test"], status: "unverified" },
  { id: 199, key: "collectedition", name: "Collect-Edition", base: "https://cards.collect-edition.com", country: "CA", collections: ["magic-in-stock-over-50"], status: "unverified" },
  { id: 200, key: "desertcitygamestcg", name: "Desert City Games", base: "https://desertcitygamestcg.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 201, key: "boutiquefdb", name: "Boutique FDB TCG", base: "https://tcg.boutiquefdb.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 202, key: "3dragons", name: "3 Dragons", base: "https://3dragons.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 203, key: "cardbrawlers", name: "Card Brawlers", base: "https://cardbrawlers.com", country: "CA", collections: ["magic-singles-1"], status: "unverified" },
  { id: 204, key: "iwantthatstuff", name: "I Want That Stuff Brandon", base: "https://iwantthatstuff.store", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 205, key: "legendarycollectables", name: "Legendary Collectables", base: "https://legendarycollectables.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 206, key: "thesidedeck", name: "The Side Deck", base: "https://thesidedeck.ca", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 207, key: "invasioncnc", name: "Invasion Inc", base: "https://invasioncnc.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 208, key: "wizardtower", name: "Wizard's Tower", base: "https://store.wizardtower.com", country: "CA", collections: ["bulk-magic-singles"], status: "unverified" },
  { id: 209, key: "dragoncardsandgames", name: "Dragon Cards & Games", base: "https://tcg.dragoncardsandgames.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 210, key: "cartessportivesrivesud", name: "Cartes Sportives Rive Sud", base: "https://cartessportivesrivesud.com", country: "CA", collections: ["magic-origins-singles"], status: "unverified" },
  { id: 211, key: "eclipsegames", name: "Eclipse Games", base: "https://eclipsegames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 212, key: "cartesleo", name: "Cartes Leo", base: "https://cartesleo.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 213, key: "kanzengames", name: "KanZenGames", base: "https://kanzengames.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 214, key: "seatoskygames", name: "SeaToSky Games", base: "https://seatoskygames.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 215, key: "manacore", name: "Boutique Manacore", base: "https://manacore.ca", country: "CA", collections: ["singles-magic-the-gathering"], status: "unverified" },
  { id: 216, key: "carlitosgamecafe", name: "Carlito's Boardgame Cafe", base: "https://carlitosgamecafe.ca", country: "CA", collections: ["in-stock-mtg"], status: "unverified" },
  { id: 217, key: "shopmancalamonk", name: "Mancala Monk Board Game Cafe", base: "https://shopmancalamonk.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 218, key: "gamebreakers", name: "Game Breakers", base: "https://gamebreakers.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 219, key: "alwaysgames", name: "Always games", base: "https://alwaysgames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 220, key: "amusengames", name: "A Muse N Games", base: "https://amusengames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 221, key: "championcitygames", name: "Champion City Games", base: "https://championcitygames.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 222, key: "silvergoblin", name: "Silver Goblin", base: "https://silvergoblin.cards", country: "CA", collections: ["all-magic-the-gathering-singles"], status: "unverified" },
  { id: 223, key: "drawforturn", name: "Draw For Turn Games", base: "https://drawforturn.ca", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 224, key: "nerdvanacardsandgames", name: "Nerdvana Cards & Games", base: "https://nerdvanacardsandgames.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 225, key: "emmettstoystop", name: "Emmett's ToyStop", base: "https://emmettstoystop.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 226, key: "tapsgames", name: "Taps Games", base: "https://tapsgames.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 227, key: "fetchshockgames", name: "Fetch & Shock Games", base: "https://fetchshockgames.com", country: "CA", collections: ["mtg-singles"], status: "unverified" },
  { id: 228, key: "untouchables", name: "Untouchables", base: "https://untouchables.ca", country: "CA", collections: ["mtg-singles-full"], status: "unverified" },
  { id: 229, key: "impulsegames", name: "Impulse Games and Hobbies", base: "https://impulsegames.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 230, key: "lamoodcomics", name: "L.A. Mood Comics and Games", base: "https://lamoodcomics.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 231, key: "kadoone", name: "KadOone", base: "https://kadoone.ca", country: "CA", collections: ["mtg-final-fantasy-singles"], status: "unverified" },
  { id: 232, key: "espercardsandgames", name: "Esper Cards & Games", base: "https://shop.espercardsandgames.com", country: "CA", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 233, key: "bentogaming", name: "Bento Gaming", base: "https://bentogaming.com", country: "CA", collections: ["mtg-singles-all-sets"], status: "unverified" },
  { id: 234, key: "game3", name: "Game 3", base: "https://game3.ca", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 235, key: "rockcitycomics", name: "Rock City Comics", base: "https://rock-city-comics.myshopify.com", country: "CA", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 236, key: "gatorbytecomputersentertainment", name: "Gator Byte", base: "https://gator-byte-computers-entertainment.myshopify.com", country: "CA", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 237, key: "kingdrug", name: "King Drug", base: "https://king-drug.myshopify.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 238, key: "headsortailsgaminginc", name: "Heads or Tails Gaming", base: "https://heads-or-tails-gaming-inc.myshopify.com", country: "CA", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 239, key: "retroempire", name: "Retro Empire Gaming", base: "https://retro-empire.nl", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 240, key: "nordiclegends", name: "Nordic Legends", base: "https://nordic-legends.com", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 241, key: "fireanddice", name: "Fire & Dice", base: "https://fireanddice.it", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 242, key: "endturn", name: "End Turn", base: "https://endturn.pt", country: "EU", collections: ["magic-single"], status: "unverified" },
  { id: 243, key: "greyogregames", name: "Grey Ogre Games", base: "https://greyogregames.com", country: "SG", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 244, key: "cardscitadel", name: "Cards Citadel", base: "https://cardscitadel.com", country: "SG", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 245, key: "onemtg", name: "One MTG", base: "https://onemtg.com.sg", country: "SG", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 247, key: "gameshaventcg", name: "Games Haven", base: "https://gameshaventcg.com", country: "SG", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 248, key: "mtgasia", name: "MTG-Asia", base: "https://mtg-asia.com", country: "SG", collections: ["mtg-singles"], status: "unverified" },
  { id: 249, key: "hideyoshitcg", name: "Hideyoshi", base: "https://hideyoshitcg.com", country: "SG", collections: ["mtg-singles"], status: "unverified" },
  { id: 250, key: "tefudagames", name: "Tefuda Games", base: "https://tefudagames.com", country: "SG", collections: ["mtg-final-fantasy-singles"], status: "unverified" },
  { id: 251, key: "cardgoblin", name: "Card Goblin", base: "https://cardgoblin.shop", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 252, key: "knightlygaming", name: "Knightly Gaming", base: "https://knightlygaming.co.uk", country: "UK", collections: ["magic-singles"], status: "unverified" },
  { id: 253, key: "unioncountygames", name: "Union County Games", base: "https://unioncountygames.com", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 254, key: "tierzerogames", name: "TierZero Games", base: "https://tierzerogames.com", country: "UK", collections: ["magic-the-gathering-single-cards"], status: "unverified" },
  { id: 255, key: "tabletopdominion", name: "Tabletop Dominion", base: "https://tabletopdominion.com", country: "UK", collections: ["magic-single"], status: "unverified" },
  { id: 256, key: "managaming", name: "Mana Gaming UK", base: "https://managaming.shop", country: "UK", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 257, key: "lvlupgaming", name: "Lvl Up Gaming", base: "https://lvlupgaming.co.uk", country: "UK", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 258, key: "londonmagictraders", name: "London Magic Traders", base: "https://londonmagictraders.com", country: "UK", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 259, key: "moxinthehole", name: "Mox in the Hole", base: "https://moxinthehole.co.uk", country: "UK", collections: ["mtg-singles-in-stock-ebay"], status: "unverified" },
  { id: 260, key: "axionnow", name: "Axion Now", base: "https://axionnow.com", country: "UK", collections: ["magic-the-gathering-all-products"], status: "unverified" },
  { id: 261, key: "gamehq", name: "Game HQ Birmingham", base: "https://game-hq.co.uk", country: "UK", collections: ["mtg-singles"], status: "unverified" },
  { id: 262, key: "mysteryninja", name: "Mystery Ninja", base: "https://mysteryninja.co.uk", country: "UK", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 263, key: "highlandergames", name: "Highlander Games", base: "https://highlandergames.co.uk", country: "UK", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 264, key: "thecardvault", name: "The Card Vault", base: "https://thecardvault.co.uk", country: "UK", collections: ["magic-the-gathering-dominaria-united"], status: "unverified" },
  { id: 265, key: "trolltradercards", name: "Troll Trader Cards", base: "https://trolltradercards.com", country: "UK", collections: ["magic-origins-promos-pori"], status: "unverified" },
  { id: 266, key: "cosmicgames", name: "Cosmic Games", base: "https://cosmicgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 267, key: "cashcardsunlimited", name: "Cash Cards Unlimited", base: "https://cashcardsunlimited.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 268, key: "evvgamingguild", name: "The Gaming Guild", base: "https://evvgamingguild.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 269, key: "impactgamingcenter", name: "Impact Gaming Center", base: "https://impactgamingcenter.gg", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 270, key: "mainephasehobbies", name: "Maine Phase Hobbies & Games", base: "https://mainephasehobbies.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 271, key: "dragonegggames", name: "Dragon Egg Games", base: "https://dragon-egg-games.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 272, key: "swordsandspoons", name: "Swords and Spoons", base: "https://swordsandspoons.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 273, key: "astralgamesonline", name: "Astral Comics & Games", base: "https://astralgamesonline.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 274, key: "dublin", name: "Littleroot Games - Dublin", base: "https://dublin.littlerootgames.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 275, key: "eclipsecardsandhobby", name: "Eclipse Cards & Hobby", base: "https://eclipsecardsandhobby.com", country: "US", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 276, key: "shippintexas", name: "Shippin Texas", base: "https://shippintexas.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 277, key: "onboardgaming", name: "On-Board Gaming", base: "https://on-boardgaming.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 278, key: "gamersgauntlet", name: "Gamer's Gauntlet", base: "https://gamersgauntlet.net", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 279, key: "thewarpgate", name: "The Warp Gate", base: "https://thewarpgate.net", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 280, key: "cardsurfergames", name: "Cardsurfer Games", base: "https://cardsurfergames.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 281, key: "accidentallycoolgames", name: "Accidentally Cool Games", base: "https://accidentallycoolgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 282, key: "galaxygamesllc", name: "Galaxy Games", base: "https://galaxygamesllc.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 283, key: "gamersparadisela", name: "Gamers Paradise", base: "https://gamersparadisela.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 284, key: "foxandfablegames", name: "Fox and Fable Games", base: "https://foxandfablegames.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 285, key: "agamesupply", name: "Andriolfs Game Supply", base: "https://agamesupply.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 286, key: "gameskingstore", name: "Games King", base: "https://gameskingstore.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 287, key: "unsettledgeeks", name: "Unsettled Geeks", base: "https://unsettledgeeks.com", country: "US", collections: ["magic-in-stock-singles"], status: "unverified" },
  { id: 288, key: "rooksgamesandmore", name: "Rooks Games and More", base: "https://rooksgamesandmore.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 289, key: "cardfathertcg", name: "Card Father Games", base: "https://cardfathertcg.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 290, key: "levelupgamesmd", name: "Level Up Games MD", base: "https://levelupgamesmd.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 291, key: "tabletopgamingcenter", name: "Tabletop Gaming Center", base: "https://tabletopgamingcenter.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 292, key: "wnygaming", name: "WNY Gaming", base: "https://wnygaming.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 293, key: "gatecitygames", name: "Gate City Games", base: "https://gatecitygames.us", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 294, key: "stupidgeeksinc", name: "Stupid Geeks", base: "https://stupidgeeksinc.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 295, key: "cardhavengames", name: "Cardhaven Games", base: "https://cardhaven-games.com", country: "US", collections: ["listed-magic-singles"], status: "unverified" },
  { id: 296, key: "triadgroup", name: "Triad Cards and Gaming", base: "https://triadgroup.shop", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 297, key: "spankyscardshop", name: "Spanky's Card Shop", base: "https://spankyscardshop.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 298, key: "hoarditall", name: "Hoard", base: "https://hoarditall.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 299, key: "progressccg", name: "Progress CCG", base: "https://progressccg.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 300, key: "digitalheroes", name: "Digital Heroes", base: "https://digitalheroes.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 301, key: "dealsndragons", name: "Deals N Dragons", base: "https://dealsndragons.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 302, key: "holohaven", name: "Holo Haven", base: "https://holohaven.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 303, key: "gameostorus", name: "Game-O-Storus", base: "https://gameostorus.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 304, key: "glaciergamesak", name: "Glacier Games", base: "https://glaciergamesak.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 305, key: "gamerealm", name: "Game Realm", base: "https://gamerealm.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 306, key: "lthobbies", name: "L.T.'s Hobbies & Games", base: "https://lthobbies.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 307, key: "gaminggiant", name: "Gaming Giant", base: "https://gaminggiant.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 308, key: "beyondadventure907", name: "Beyond Adventure Games", base: "https://beyondadventure907.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 309, key: "pro", name: "Wild Things Games", base: "https://pro.wildthingsgames.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 310, key: "dynamiccardcollectors", name: "Dynamic Card Collectors", base: "https://dynamiccardcollectors.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 311, key: "tier1games", name: "Tier 1 Games", base: "https://tier1games.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 312, key: "lapinetabletopgaming", name: "La Pine Tabletop Gaming", base: "https://lapinetabletopgaming.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 313, key: "forgottenpathgames", name: "Forgotten Path Games", base: "https://forgottenpathgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 314, key: "blackswampgames", name: "Black Swamp Games", base: "https://blackswampgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 315, key: "dinoscardsandcollectibles", name: "Dino's Cards & Collectibles", base: "https://dinoscardsandcollectibles.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 316, key: "graygauntletgames", name: "Gray Gauntlet Games", base: "https://graygauntletgames.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 317, key: "baxtersrealm", name: "Baxter's Cards & Games", base: "https://baxtersrealm.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 318, key: "gamesatthevault", name: "Games at the Vault (Seibert Technologies)", base: "https://gamesatthevault.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 319, key: "colestreetgamevault", name: "Cole Street Game Vault", base: "https://colestreetgamevault.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 320, key: "smokeandmirrorshobby", name: "Smoke and Mirrors Hobby", base: "https://smokeandmirrorshobby.com", country: "US", collections: ["mtg-in-stock"], status: "unverified" },
  { id: 321, key: "gglehi", name: "Game Grid Lehi", base: "https://store.gglehi.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 322, key: "primetimemagic", name: "Prime Time Magic", base: "https://primetimemagic.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 323, key: "fabricatorsforge", name: "Fabricator's Forge", base: "https://shop.fabricatorsforge.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 324, key: "galacticgamez", name: "Galactic Gamez", base: "https://galacticgamez.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 325, key: "larrysgamestore", name: "Larry's Game Store", base: "https://larrysgamestore.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 326, key: "hilogameshop", name: "Hilo Game Shop", base: "https://hilogameshop.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 327, key: "mindgamesandmagic", name: "Mindgames and Magic", base: "https://mindgamesandmagic.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 328, key: "redfoxgamingonline", name: "Red Fox Gaming", base: "https://redfoxgamingonline.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 329, key: "bentonville", name: "Gear Gaming Bentonville", base: "https://bentonville.geargamingstore.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 330, key: "evanstongames", name: "Evanston Games", base: "https://evanstongames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 331, key: "castlegameshoppe", name: "Castle Game Shoppe", base: "https://castlegameshoppe.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 332, key: "day2lgs", name: "Day2 Cards and Games", base: "https://day2lgs.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 333, key: "fayetteville", name: "Gear Gaming Fayetteville", base: "https://fayetteville.geargamingstore.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 334, key: "phatcatzgaming", name: "Phat Catz Gaming", base: "https://phatcatzgaming.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 335, key: "blackvaultgaming", name: "Black Vault Gaming", base: "https://blackvaultgaming.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 336, key: "alchemistsrefuge", name: "Alchemist's Refuge", base: "https://alchemistsrefuge.shop", country: "US", collections: ["stock-case-mtg"], status: "unverified" },
  { id: 337, key: "oldschoolgamesandcards", name: "Old School Games and Cards", base: "https://oldschoolgamesandcards.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 338, key: "dragonsdenshop", name: "Dragons Den Shop", base: "https://dragonsdenshop.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 339, key: "onendunncards", name: "OneNDunn Cards", base: "https://onendunncards.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 340, key: "five6gaming", name: "FIVE6 Gaming", base: "https://five6gaming.com", country: "US", collections: ["in-stock-mtg"], status: "unverified" },
  { id: 341, key: "motorcitygaming", name: "Motor City Gaming", base: "https://motorcitygaming.net", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 342, key: "balancegamingfl", name: "Balance Martial Arts and Gaming", base: "https://balancegamingfl.com", country: "US", collections: ["mtg-singles-20-and-up"], status: "unverified" },
  { id: 343, key: "boardwalkgames", name: "Boardwalk Games", base: "https://boardwalk-games.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 344, key: "gravitasgaming", name: "Gravitas Games", base: "https://gravitasgaming.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 345, key: "clockworkgaming", name: "Clockwork Games & Events", base: "https://clockworkgaming.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 346, key: "stgcards", name: "STG Cards and Collectables", base: "https://stgcards.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 347, key: "deckdepottcg", name: "The Deck Depot Trading Card Lounge", base: "https://deckdepottcg.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 348, key: "laststandcollectibles", name: "Last Stand Collectibles", base: "https://laststandcollectibles.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 349, key: "blackdragongames", name: "Black Dragon Games", base: "https://blackdragongames.net", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 350, key: "animeimports", name: "Anime Imports", base: "https://animeimports.net", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 351, key: "mimicsmarket", name: "Mimic's Market Cards & Games", base: "https://mimicsmarket.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 352, key: "nutmeggames", name: "Nutmeg Games", base: "https://nutmeggames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 353, key: "realitybreakgames", name: "Reality Break Games", base: "https://realitybreakgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 354, key: "thehaventabletop", name: "The Haven Games", base: "https://thehaventabletop.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 355, key: "tacomagames", name: "Tacoma Games", base: "https://tacoma-games.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 356, key: "columbuscardshop", name: "Columbus Card Shop", base: "https://columbuscardshop.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 357, key: "phantasmalv", name: "Phantasma", base: "https://phantasmalv.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 358, key: "wolfdentcg", name: "Wolf Den Gaming", base: "https://wolfdentcg.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 359, key: "cardquestlgs", name: "Card Quest", base: "https://cardquestlgs.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 360, key: "moonshotgamestore", name: "Moonshot Games", base: "https://moonshotgamestore.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 361, key: "animalhousecards", name: "Animal House Cards", base: "https://animalhousecards.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 362, key: "littlespectacles", name: "Little Spectacles", base: "https://littlespectacles.shop", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 363, key: "sealedrelics", name: "Sealed Relics", base: "https://sealedrelics.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 364, key: "blackmanamarket", name: "Black Mana Market", base: "https://blackmanamarket.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 365, key: "bricksandheroes", name: "Bricks & Heroes", base: "https://bricksandheroes.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 366, key: "millersccct", name: "Miller's Comics, Cards, Collectibles", base: "https://millersccct.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 367, key: "primalcards", name: "Primal Cards & Collectables", base: "https://primalcards.net", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 368, key: "gamefellastcgandgames", name: "Gamefellas", base: "https://gamefellastcgandgames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 369, key: "cardboardhorde", name: "Cardboard Horde", base: "https://cardboardhorde.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 370, key: "e4cards", name: "E4 Cards & More", base: "https://e4cards.com", country: "US", collections: ["m-tg-singles"], status: "unverified" },
  { id: 371, key: "eternalgameschesterfield", name: "Eternal Games Chesterfield", base: "https://eternalgameschesterfield.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 372, key: "summitgames", name: "Super Heroes Comics Cards and Games", base: "https://summitgames.gg", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 373, key: "lotusgames", name: "Lotus Games (Kalispell)", base: "https://lotusgames.shop", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 374, key: "showdownvaluecardsandgames", name: "Showdown Value Cards & Games", base: "https://showdownvaluecardsandgames.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 375, key: "ruston", name: "A&H Ruston", base: "https://ruston.ah.games", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 376, key: "reddhill", name: "Reddhill Games & Electronics", base: "https://reddhill.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 377, key: "paradisehobbiesllc", name: "Paradise Hobbies", base: "https://paradisehobbiesllc.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 378, key: "prosoulgames", name: "ProSoul Games", base: "https://prosoulgames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 379, key: "sydequest", name: "Sydequest Games", base: "https://sydequest.games", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 380, key: "vaultgamestore", name: "Vault Game Store", base: "https://vaultgamestore.com", country: "US", collections: ["mtg-singles-all"], status: "unverified" },
  { id: 381, key: "collectem", name: "Collect'eM Card & Hobby", base: "https://collect-em.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 382, key: "zcgamestcg", name: "ZCGames", base: "https://zcgamestcg.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 383, key: "ettingames", name: "Ettin Games", base: "https://ettingames.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 384, key: "madtownhobby", name: "Madtown Hobby", base: "https://madtownhobby.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 385, key: "thedragonsvaultofnj", name: "The Dragon's Vault of NJ", base: "https://thedragonsvaultofnj.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 386, key: "constellationcollectivesac", name: "Constellation Collective Sacramento", base: "https://constellationcollectivesac.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 387, key: "skyboxct", name: "Skybox Collectibles", base: "https://skyboxct.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 388, key: "capefearcollectibles", name: "Cape Fear Collectibles", base: "https://capefearcollectibles.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 389, key: "vegas", name: "Vegas Singles", base: "https://vegas.singles", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 390, key: "epikcg", name: "Epik Cards and Games", base: "https://epikcg.com", country: "US", collections: ["magic-the-gathering-singles-in-stock"], status: "unverified" },
  { id: 391, key: "divinegamez", name: "Divine Gamez", base: "https://divinegamez.com", country: "US", collections: [], platform: "shadowpos", status: "unverified" },
  { id: 392, key: "ironlioncollectibles", name: "Iron Lion Collectibles", base: "https://ironlioncollectibles.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 393, key: "alohacardshop", name: "Aloha Card Shop", base: "https://alohacardshop.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 394, key: "finalround", name: "Final Round Game Shop", base: "https://finalround.games", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 395, key: "brickandboardgames", name: "Brick & Board Games and Cards", base: "https://brickandboardgames.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 396, key: "gamersgrove", name: "Gamers Grove", base: "https://gamersgrove.com", country: "US", collections: ["magic-singles-instock"], status: "unverified" },
  { id: 397, key: "mythicforgegames", name: "Mythic Forge Gaming", base: "https://mythicforgegames.com", country: "US", collections: ["mtg-singles-all-products"], status: "unverified" },
  { id: 398, key: "gamegridif", name: "Game Grid Idaho Falls", base: "https://gamegridif.com", country: "US", collections: ["mtg-singles-in-stock"], status: "unverified" },
  { id: 399, key: "shufflenroll", name: "Shuffle N Roll", base: "https://shufflenroll.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 400, key: "cardmonstergames", name: "CM Games (Card Monster Games)", base: "https://cardmonstergames.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 401, key: "mostexcellentgaming", name: "Most Excellent Gaming", base: "https://mostexcellentgaming.com", country: "US", collections: ["mtg-singles-instock"], status: "unverified" },
  { id: 402, key: "zamliytcg", name: "Zamliy TCG", base: "https://zamliytcg.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 403, key: "superanimestore", name: "Super Anime Store", base: "https://superanimestore.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 404, key: "hobbyvault", name: "Hobby Vault", base: "https://hobbyvault.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 405, key: "joshscards", name: "Josh's Cards", base: "https://joshscards.com", country: "US", collections: ["latest-magic-singles"], status: "unverified" },
  { id: 406, key: "bluejayscauldron", name: "Blue Jay's Cauldron", base: "https://bluejayscauldron.com", country: "US", collections: ["mtg-singles"], status: "unverified" },
  { id: 407, key: "knightanddaygames", name: "Knight & Day Games", base: "https://knightanddaygames.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 408, key: "thehubtcg", name: "The Hub TCG", base: "https://thehubtcg.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 409, key: "burbankcards", name: "Burbank Sportscards", base: "https://burbankcards.com", country: "US", collections: ["magic-the-gathering"], status: "unverified" },
  { id: 410, key: "envycardstore", name: "Envy Cards", base: "https://envycardstore.com", country: "US", collections: ["magic-singles"], status: "unverified" },
  { id: 411, key: "thenerdmerchant", name: "The Nerd Merchant", base: "https://thenerdmerchant.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 412, key: "foxfablehaven", name: "Fox Fable Haven", base: "https://foxfablehaven.com", country: "US", collections: ["bulk-magic"], status: "unverified" },
  { id: 413, key: "deepdivegames", name: "Deep Dive Games", base: "https://deep-dive-games.myshopify.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
  { id: 414, key: "guardiangamesllc", name: "Guardian Games", base: "https://guardian-games-llc.myshopify.com", country: "US", collections: ["magic-the-gathering-singles"], status: "unverified" },
];
