import * as C from "../../src/lib/constants";
let fails = 0;
const eq = (a: unknown, b: unknown, m: string) => { if (JSON.stringify(a) !== JSON.stringify(b)) { fails++; console.log("FAIL", m, JSON.stringify(a), "!=", JSON.stringify(b)); } };
// synonyms unique
const seen = new Map<string, string>(); let dup = 0;
for (const t of C.TREATMENTS) for (const s of t.syn) { const k = (C.fold(s.replace(/\*$/, "")) + (s.endsWith("*") ? " *" : "")); if (seen.has(k) && seen.get(k) !== t.key) { dup++; console.log("DUP SYN", k, seen.get(k), t.key); } seen.set(k, t.key); }
eq(dup, 0, "no duplicate synonym");
eq(C.TREATMENT_KEYS.length, new Set(C.TREATMENT_KEYS).size, "unique keys");
console.log("treatments", C.TREATMENTS.length, "synonyms", C.TREATMENT_BY_SYNONYM.size, "foil patterns", C.FOIL_PATTERN_KEYS.size, "chase", C.TREATMENTS.filter(t => t.chase).length);
eq(C.FORMATS.length, 22, "22 formats");
eq(C.nsort("2") < C.nsort("10") && C.nsort("10") < C.nsort("10★") && C.nsort("10★") < C.nsort("10a") && C.nsort("10a") < C.nsort("11"), true, "nsort order");
eq([C.nsort("A39") > C.nsort("999"), C.nsort("165p"), C.nsort("155s"), C.nsort("KHC-29") > 1e9, C.nsort(null)], [true, 165017, 155020, true, 2e9], "nsort values");
eq([C.nkey("029/281"), C.nkey("0205"), C.nkey("7 // 2"), C.nkey("213★"), C.nkey("A39"), C.nkey("551a"), C.nkey("KHC-29"), C.nkey(null), C.nkey("")], ["29", "205", "7", "213", "a39", "551a", "khc-29", null, null], "nkey");
eq([C.displayName("transform", "Delver of Secrets // Insectile Aberration"), C.displayName("split", "Fire // Ice"), C.displayName("normal", "Sol Ring"), C.displayName("reversible_card", "Megatron // Megatron")], ["Delver of Secrets", "Fire // Ice", "Sol Ring", "Megatron"], "displayName");
eq([C.effectiveRarity({ tcg: "P", scry: "rare", cls: 0 }), C.effectiveRarity({ tcg: "L", scry: "common", cls: 0 }), C.effectiveRarity({ tcg: "S", scry: null, cls: 0 }), C.effectiveRarity({ tcg: "R", scry: null, cls: 1 }), C.effectiveRarity({ tcg: null, scry: null, cls: 0 })], ["R", "L", "S", "T", "S"], "effectiveRarity");
eq(["Artifact Creature — Golem", "Artifact Land", "Kindred Instant", "Tribal Instant — Elf", "Summon Wolf", "Legendary Planeswalker — Jace", "Basic Land — Forest", "Battle — Siege", "Plane — Dominaria", "Legendary Creature — Human // Land", "Instant", "Interrupt"].map(C.primaryType),
  ["creature", "land", "instant", "instant", "creature", "planeswalker", "land", "battle", "other", "creature", "instant", "instant"], "primaryType");
eq(C.legalString({ standard: "not_legal", future: "not_legal", historic: "not_legal", timeless: "not_legal", gladiator: "not_legal", pioneer: "not_legal", modern: "not_legal", legacy: "banned", pauper: "not_legal", vintage: "restricted", penny: "not_legal", commander: "banned", oathbreaker: "banned", standardbrawl: "not_legal", brawl: "not_legal", competitivebrawl: "not_legal", alchemy: "not_legal", paupercommander: "not_legal", duel: "banned", oldschool: "not_legal", premodern: "not_legal", predh: "banned", tlr: "banned" }).legal, "NNNNNNNBNRNBBNNNNNBNBB", "Black Lotus legality vector");
eq([C.legalityOf(undefined, "modern"), C.legalityOf("LLLLLLLLLLLLLLLLLLLLLL", "tlr"), C.legalityOf("L", "tlr"), C.isPlayable("NNNNNNNBNRNBBNNNNNBNBB", "vintage"), C.isPlayable("NNNNNNNBNRNBBNNNNNBNBB", "legacy")], ["unknown", "legal", "unknown", true, false], "legalityOf");
eq([C.classifyGroup({ name: "Mystery Booster Commander Edition" }), C.classifyGroup({ name: "Commander Legends: Battle for Baldur's Gate" }), C.classifyGroup({ name: "Commander: Murders at Karlov Manor" }), C.classifyGroup({ name: "Planechase: Universes Beyond: Doctor Who" }), C.classifyGroup({ name: "Promo Pack: Core Set 2020" }), C.classifyGroup({ name: "Secret Lair Drop Series" }), C.classifyGroup({ name: "Mystery Booster 2 Playtest Cards" }), C.classifyGroup({ name: "Reality Fracture" }), C.classifyGroup({ name: "Totally New Bucket", publishedOn: "2026-10-07T00:00:00.123Z" })],
  ["masters", "masters", "commander", "deck", "promo-pack", "secret-lair", "unset", "expansion", "promo"], "classifyGroup");
eq(["Secret Lair Drop: Foo", "Modern Horizons 3 Collector Booster Display", "Play Booster Pack", "Bundle: Foo", "Commander Deck - Foo", "Foo Prerelease Pack", "Draft Night"].map(C.sealedKind), ["Secret Lair Drop", "Booster Box", "Booster Pack", "Bundle", "Commander Deck", "Prerelease Pack", "Other"], "sealedKind");
eq([C.colorMask(["White", "Blue"]), C.colorMask(["G", "R"]), C.colorsOfMask(31).length, C.matchesColorPage(0, "colorless"), C.matchesColorPage(3, "white"), C.matchesColorPage(3, "multicolor"), C.identityFits(1, 3), C.identityFits(4, 3), C.identityName(7)], [3, 24, 5, true, false, true, true, false, "Esper"], "colours");
eq([C.unitKey(2831, "F"), C.parseUnitKey("2831.1"), C.parseUnitKey("x"), C.uidOf(2831, "F"), C.unitOfUid(5663)], ["2831.1", { id: 2831, finish: "F" }, null, 5663, { id: 2831, finish: "F" }], "units");
eq([C.finishLabel({ flags: 0, treat: ["surge"] }, "F"), C.finishLabel({ flags: C.CARD_FLAGS.ETCHED, treat: ["etched"] }, "F"), C.finishLabel({ flags: 0, treat: [] }, "F"), C.finishLabel({ flags: 0, treat: [] }, "N"), C.printingOf(["galaxy", "borderless"]), C.printingOf([]), C.treatmentLabel(["galaxy", "borderless"])], ["Surge Foil", "Foil Etched", "Foil", "Non-foil", "borderless", "standard", "Borderless · Galaxy Foil"], "labels");
eq([C.parseFinishParam("Foil"), C.parseFinishParam("etched"), C.parseFinishParam("x")], [{ finish: "F", etched: false }, { finish: "F", etched: true }, null], "parseFinishParam");
eq(C.oracleFlags({ typeLine: "Legendary Creature — Human Wizard", oracleText: "", keywords: [], power: "2", toughness: "2", reserved: false, gameChanger: false, commanderLegal: true }) & C.ORACLE_FLAGS.COMMANDER, 4, "commander legendary creature");
eq(C.oracleFlags({ typeLine: "Legendary Planeswalker — Teferi", oracleText: "Teferi can be your commander.", keywords: [], power: null, toughness: null, reserved: false, gameChanger: false, commanderLegal: true }) & C.ORACLE_FLAGS.COMMANDER, 4, "commander text");
eq(C.oracleFlags({ typeLine: "Legendary Planeswalker — Jace", oracleText: "", keywords: [], power: null, toughness: null, reserved: false, gameChanger: false, commanderLegal: true }) & C.ORACLE_FLAGS.COMMANDER, 0, "jace not commander");
eq(C.oracleFlags({ typeLine: "Creature — Human // Legendary Creature — Werewolf", oracleText: "", keywords: [], power: "2", toughness: "2", reserved: false, gameChanger: false, commanderLegal: true }) & C.ORACLE_FLAGS.COMMANDER, 0, "back-face-only legend not commander");
eq(C.nameForms({ name: "Sheoldred, the Apocalypse", alt: "Khan, Engineered Evil", tcgName: "Khan, Engineered Evil - Sheoldred, the Apocalypse (Borderless)" }).slice(0, 3), ["sheoldred the apocalypse", "khan engineered evil", "khan engineered evil sheoldred the apocalypse borderless"], "nameForms");
console.log(fails ? `${fails} FAILURES` : "all constants checks pass");
