// Condense raw probe output (scripts/probe-shipping-rates.ts) into the postage
// snapshot the site imports: src/lib/shipping-rates.json.
//
// Usage:
//   npx tsx scripts/build-shipping-rates.ts AU.json US.json UK.json CA.json EU.json SG.json
//   npx tsx scripts/build-shipping-rates.ts shipping-au.json --summary=diff.md
//   npx tsx scripts/build-shipping-rates.ts shipping-au.json --out=/tmp/new.json --check
// Options:
//   --out=<path>      where to write (default src/lib/shipping-rates.json)
//   --base=<path>     the snapshot to merge into (default: the --out file, if it exists).
//                     Only the markets present in the inputs are replaced; the
//                     others are kept as they were.
//   --summary=<path>  also write the change report as Markdown (for $GITHUB_STEP_SUMMARY)
//   --check           write nothing to --out; just report what would change
//   --add-carts       a store measured in more than one input keeps the carts of
//                     all of them, a later input winning on the same cart
//                     (subtotal and card count). For threshold rungs re-probed
//                     after a full run. Without it the later input replaces the
//                     store — right for a re-run that corrects a bad one.
//
// A run that covers every configured store of a market replaces that market;
// a partial run (probe --store=…) replaces only the stores it measured.
//
// The raw files are several MB each and are NOT committed — the probe workflow
// (.github/workflows/shipping-rates.yml) uploads them as an artifact. Only the
// condensed snapshot is checked in. See lib/shipping-snapshot.ts for its shape
// and lib/shipping.ts for how it is read.
export {};
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { STORES } from "../src/lib/stores";
import type { Country } from "../src/lib/country";
import { PROBE_ADDRESSES } from "../src/lib/shipping-probe";
import { condenseStore, type ProbeStoreInput, type ShippingSnapshot } from "../src/lib/shipping-snapshot";
import { shippingFor, shippingSummary, formatMeasuredDate } from "../src/lib/shipping";
import { formatMoney } from "../src/lib/format-currency";

function arg(name: string): string | undefined {
  const hit = process.argv.slice(2).find((a) => a === `--${name}` || a.startsWith(`--${name}=`));
  if (!hit) return undefined;
  const eq = hit.indexOf("=");
  return eq < 0 ? "" : hit.slice(eq + 1);
}

const inputs = process.argv.slice(2).filter((a) => !a.startsWith("--"));
if (!inputs.length) {
  console.error("Usage: npx tsx scripts/build-shipping-rates.ts <probe-output.json>... [--out=] [--base=] [--summary=] [--check]");
  process.exit(2);
}
const outPath = resolve(arg("out") || "src/lib/shipping-rates.json");
const basePath = arg("base") ? resolve(arg("base")!) : outPath;
const check = arg("check") !== undefined;
const addCarts = arg("add-carts") !== undefined;

const base: ShippingSnapshot | null = existsSync(basePath) ? JSON.parse(readFileSync(basePath, "utf8")) : null;
const next: ShippingSnapshot = {
  version: 1,
  note:
    "GENERATED by scripts/build-shipping-rates.ts from scripts/probe-shipping-rates.ts runs — do not hand-edit. " +
    "Per store: the carts measured ([subtotalCents, items]) and, per group of addresses quoted identically, the cheapest " +
    "non-letter rate (std: [cents, nameIndex, tracked]) and cheapest untracked letter (ltr: [cents, nameIndex]) for each cart. " +
    "Read by src/lib/shipping.ts.",
  markets: { ...(base?.markets ?? {}) },
  stores: { ...(base?.stores ?? {}) },
};

const replaced = new Set<Country>();
const fullRun = new Set<Country>();
const measured = new Map<string, ProbeStoreInput>();
// The same cart, measured twice: [subtotal, cards] (a scenario that reused an
// earlier cart, or failed to build one, has none of its own).
const cartKey = (x: ProbeStoreInput["scenarios"][number]) => (x.sameCartAs || x.items <= 0 ? null : `${x.subtotalCents}/${x.items}`);
for (const f of inputs) {
  const raw = JSON.parse(readFileSync(resolve(f), "utf8")) as { market: Country; stores: ProbeStoreInput[] };
  const market = raw.market;
  if (!PROBE_ADDRESSES[market as keyof typeof PROBE_ADDRESSES]) throw new Error(`${f}: unknown market ${market}`);
  // A FULL-market run (every configured store of the market in it) replaces
  // the market as a whole, so a store dropped from lib/stores.ts since the last
  // run does not linger. A partial run (--store=cardgoblin) only replaces the
  // stores it measured: wiping the rest would send every other store in the
  // market back to an estimate.
  const inRun = new Set(raw.stores.map((s) => s.key));
  const full = STORES.filter((r) => r.country === market).every((r) => inRun.has(r.key));
  if (full && !fullRun.has(market)) {
    for (const [k, s] of Object.entries(next.stores)) if (s.market === market) delete next.stores[k];
    fullRun.add(market);
  }
  replaced.add(market);
  for (const s of raw.stores) {
    const prev = measured.get(s.key);
    if (addCarts && prev && prev.market === market) {
      const again = new Set(s.scenarios.map(cartKey).filter(Boolean));
      measured.set(s.key, {
        ...s,
        market,
        measuredAt: [prev.measuredAt, s.measuredAt].sort().at(-1)!,
        scenarios: [...prev.scenarios.filter((x) => { const k = cartKey(x); return k && !again.has(k); }), ...s.scenarios],
      });
    } else {
      measured.set(s.key, { ...s, market });
    }
  }
}
for (const [key, s] of measured) next.stores[key] = condenseStore(s);
// A market with no full run among the inputs is a partial refresh.
const partial = new Set([...replaced].filter((m) => !fullRun.has(m)));
for (const market of replaced) {
  // A full run is as fresh as its newest store; a partial one only as fresh as
  // the OLDEST store in the market, since the rest were measured before it.
  const dates = Object.values(next.stores)
    .filter((s) => s.market === market && s.measuredAt)
    .map((s) => s.measuredAt)
    .sort();
  next.markets[market] = {
    measuredAt: (partial.has(market) ? dates[0] : dates[dates.length - 1]) ?? "",
    addresses: PROBE_ADDRESSES[market as keyof typeof PROBE_ADDRESSES].map((a) => ({ id: a.id, label: a.label })),
  };
}

// Keep only stores that are still configured, in a stable order.
const configured = new Set(STORES.map((r) => r.key));
const gone = Object.keys(next.stores).filter((k) => !configured.has(k));
for (const k of gone) delete next.stores[k];
next.stores = Object.fromEntries(Object.entries(next.stores).sort(([a], [b]) => a.localeCompare(b)));
const missing = STORES.filter((r) => !next.stores[r.key]).map((r) => r.key);

// ── Change report ───────────────────────────────────────────────────────────
// A table of every store whose one-card postage changed, then the changes
// worth a human look before the refresh is committed: a store that newly
// "does not post" (it drops out of Best Basket) and a one-card rate that moved
// by more than half (a probe that measured the wrong cart, or a real change).
const lines: string[] = [];
const fmt = (c: number | null | undefined, cur: string) => (c == null ? "—" : formatMoney(c, cur));
interface Line {
  text: string;
  noPost: boolean;
  cents: number | null; // 1-card postage at the highest region; null = not measured / no postage
  currency: string;
}
const lineOf = (snap: ShippingSnapshot | null, key: string): Line | null => {
  if (!snap?.stores[key]) return null;
  const s = shippingSummary(key, snap);
  if (s.basis === "no-post") return { text: `no postage (${s.note ?? "does not post"})`, noPost: true, cents: null, currency: s.currency };
  if (s.basis === "estimate") return { text: `not measured${s.note ? ` (${s.note})` : ""}`, noPost: false, cents: null, currency: s.currency };
  const q = shippingFor(key, { subtotalCents: s.oneCardSubtotalCents ?? 100, items: 1 }, {}, snap);
  const free = s.free?.fromCents != null ? `free from ${fmt(s.free.fromCents, s.currency)}` : "no free threshold";
  const regions = s.notServed?.length ? ` · does not post to ${s.notServed.join(", ")}` : "";
  return {
    text: `1 card ${q.upTo ? "up to " : ""}${fmt(q.cents, s.currency)} (${q.label}) · ${free}${regions}`,
    noPost: !!q.unavailable,
    cents: q.unavailable ? null : q.cents,
    currency: s.currency,
  };
};
lines.push(`## Postage snapshot — ${[...replaced].map((m) => (partial.has(m) ? `${m} (partial run)` : m)).join(", ")}`);
lines.push("");
lines.push("| Store | Market | Before | After |");
lines.push("|---|---|---|---|");
let changed = 0;
const flags: string[] = [];
for (const key of Object.keys(next.stores)) {
  if (!replaced.has(next.stores[key].market)) continue;
  const before = lineOf(base, key);
  const after = lineOf(next, key);
  const bt = before?.text ?? "not in snapshot";
  const at = after?.text ?? "not in snapshot";
  if (bt === at) continue;
  changed++;
  lines.push(`| ${key} | ${next.stores[key].market} | ${bt} | ${at} |`);
  if (after?.noPost && !before?.noPost) flags.push(`- **${key}** newly does not post: ${at} — check by hand; it drops out of Best Basket`);
  if (before?.cents != null && after?.cents != null && before.currency === after.currency) {
    const lo = Math.min(before.cents, after.cents);
    const hi = Math.max(before.cents, after.cents);
    if (hi > 0 && (lo === 0 ? hi >= 100 : hi / lo > 1.5)) {
      flags.push(`- **${key}** one-card postage moved ${fmt(before.cents, before.currency)} → ${fmt(after.cents, after.currency)} (more than 50%)`);
    }
  }
}
if (!changed) lines.push("| — | — | no change | — |");
lines.push("");
lines.push(flags.length ? "### Needs a look before committing" : "### Nothing flagged (no store newly without postage, no one-card move over 50%)");
if (flags.length) lines.push("", ...flags);
lines.push("");
for (const m of replaced) {
  const info = next.markets[m];
  if (info) lines.push(`- ${m}: measured ${formatMeasuredDate(info.measuredAt)}${partial.has(m) ? " (oldest store in the market — a partial run)" : ""}`);
}
if (gone.length) lines.push(`- Dropped (no longer in lib/stores.ts): ${gone.join(", ")}`);
if (missing.length) lines.push(`- Not in the snapshot (shown as estimates): ${missing.join(", ")}`);
const report = lines.join("\n") + "\n";
console.log(report);
const summaryPath = arg("summary");
if (summaryPath) writeFileSync(resolve(summaryPath), report, { flag: "a" });

// One store per line: small, and a refresh diffs store by store in git.
const json =
  "{\n" +
  `"version": ${next.version},\n"note": ${JSON.stringify(next.note)},\n"markets": ${JSON.stringify(next.markets)},\n"stores": {\n` +
  Object.entries(next.stores)
    .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(",\n") +
  "\n}\n}\n";
if (check) {
  console.log(`--check: ${changed} store(s) would change; nothing written (${(json.length / 1024).toFixed(1)} KB).`);
} else {
  writeFileSync(outPath, json);
  console.log(`Wrote ${outPath} (${(json.length / 1024).toFixed(1)} KB, ${Object.keys(next.stores).length} stores).`);
}
